<a href="https://colab.research.google.com/github/SagarHadge0/NLP-projects/blob/main/Text_Generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout,Bidirectional
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import regularizers
import tensorflow.keras.utils as ku
from keras.utils import to_categorical
import numpy as np

In [4]:
data = open('/content/sonnets (1).txt').read()

In [5]:
data

"\tSONNETS\n\n\n\nTO THE ONLY BEGETTER OF\nTHESE INSUING SONNETS\nMR. W. H. ALL HAPPINESS\nAND THAT ETERNITY\nPROMISED BY\nOUR EVER-LIVING POET WISHETH\nTHE WELL-WISHING\nADVENTURER IN\nSETTING FORTH\nT. T.\n\n\nI.\n\nFROM fairest creatures we desire increase,\nThat thereby beauty's rose might never die,\nBut as the riper should by time decease,\nHis tender heir might bear his memory:\nBut thou, contracted to thine own bright eyes,\nFeed'st thy light'st flame with self-substantial fuel,\nMaking a famine where abundance lies,\nThyself thy foe, to thy sweet self too cruel.\nThou that art now the world's fresh ornament\nAnd only herald to the gaudy spring,\nWithin thine own bud buriest thy content\nAnd, tender churl, makest waste in niggarding.\n  Pity the world, or else this glutton be,\n  To eat the world's due, by the grave and thee.\n\nII.\n\nWhen forty winters shall beseige thy brow,\nAnd dig deep trenches in thy beauty's field,\nThy youth's proud livery, so gazed on now,\nWill be a 

In [6]:
corpus = data.lower().split("\n")

In [7]:
corpus

['\tsonnets',
 '',
 '',
 '',
 'to the only begetter of',
 'these insuing sonnets',
 'mr. w. h. all happiness',
 'and that eternity',
 'promised by',
 'our ever-living poet wisheth',
 'the well-wishing',
 'adventurer in',
 'setting forth',
 't. t.',
 '',
 '',
 'i.',
 '',
 'from fairest creatures we desire increase,',
 "that thereby beauty's rose might never die,",
 'but as the riper should by time decease,',
 'his tender heir might bear his memory:',
 'but thou, contracted to thine own bright eyes,',
 "feed'st thy light'st flame with self-substantial fuel,",
 'making a famine where abundance lies,',
 'thyself thy foe, to thy sweet self too cruel.',
 "thou that art now the world's fresh ornament",
 'and only herald to the gaudy spring,',
 'within thine own bud buriest thy content',
 'and, tender churl, makest waste in niggarding.',
 '  pity the world, or else this glutton be,',
 "  to eat the world's due, by the grave and thee.",
 '',
 'ii.',
 '',
 'when forty winters shall beseige thy b

In [8]:
len(corpus)

2634

In [9]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)
total_words = len(tokenizer.word_index) + 1

In [10]:
total_words

3375

In [11]:
tokenizer.word_index

{'and': 1,
 'the': 2,
 'to': 3,
 'of': 4,
 'my': 5,
 'i': 6,
 'in': 7,
 'that': 8,
 'thy': 9,
 'thou': 10,
 'with': 11,
 'for': 12,
 'is': 13,
 'not': 14,
 'love': 15,
 'but': 16,
 'a': 17,
 'me': 18,
 'thee': 19,
 'so': 20,
 'be': 21,
 'as': 22,
 'all': 23,
 'you': 24,
 'his': 25,
 'which': 26,
 'when': 27,
 'it': 28,
 'this': 29,
 'by': 30,
 'your': 31,
 'doth': 32,
 'do': 33,
 'from': 34,
 'on': 35,
 'or': 36,
 'no': 37,
 'then': 38,
 'have': 39,
 'what': 40,
 'are': 41,
 'if': 42,
 'more': 43,
 'mine': 44,
 'their': 45,
 'shall': 46,
 'sweet': 47,
 'time': 48,
 'will': 49,
 'they': 50,
 'beauty': 51,
 'nor': 52,
 'eyes': 53,
 'art': 54,
 'her': 55,
 'heart': 56,
 'yet': 57,
 'o': 58,
 'than': 59,
 'can': 60,
 'should': 61,
 'thine': 62,
 'now': 63,
 'where': 64,
 'make': 65,
 'one': 66,
 'hath': 67,
 'he': 68,
 'fair': 69,
 'still': 70,
 'how': 71,
 'eye': 72,
 'him': 73,
 'like': 74,
 'true': 75,
 'see': 76,
 'am': 77,
 'she': 78,
 'those': 79,
 'though': 80,
 'being': 81,
 'some'

In [12]:
input_sequences =[]
for line in corpus:
  token_list = tokenizer.texts_to_sequences([line])[0]
  for i in range(1,len(token_list)):
    n_gram_sequence = token_list[:i+1]
    input_sequences.append(n_gram_sequence)

In [13]:
input_sequences

[[3, 2],
 [3, 2, 313],
 [3, 2, 313, 1375],
 [3, 2, 313, 1375, 4],
 [118, 1376],
 [118, 1376, 878],
 [1377, 1378],
 [1377, 1378, 1379],
 [1377, 1378, 1379, 23],
 [1377, 1378, 1379, 23, 1380],
 [1, 8],
 [1, 8, 517],
 [1381, 30],
 [126, 186],
 [126, 186, 278],
 [126, 186, 278, 635],
 [126, 186, 278, 635, 1382],
 [2, 98],
 [2, 98, 879],
 [1383, 7],
 [1384, 279],
 [880, 880],
 [34, 418],
 [34, 418, 881],
 [34, 418, 881, 166],
 [34, 418, 881, 166, 214],
 [34, 418, 881, 166, 214, 518],
 [8, 882],
 [8, 882, 135],
 [8, 882, 135, 353],
 [8, 882, 135, 353, 103],
 [8, 882, 135, 353, 103, 156],
 [8, 882, 135, 353, 103, 156, 199],
 [16, 22],
 [16, 22, 2],
 [16, 22, 2, 883],
 [16, 22, 2, 883, 61],
 [16, 22, 2, 883, 61, 30],
 [16, 22, 2, 883, 61, 30, 48],
 [16, 22, 2, 883, 61, 30, 48, 636],
 [25, 314],
 [25, 314, 637],
 [25, 314, 637, 103],
 [25, 314, 637, 103, 200],
 [25, 314, 637, 103, 200, 25],
 [25, 314, 637, 103, 200, 25, 280],
 [16, 10],
 [16, 10, 884],
 [16, 10, 884, 3],
 [16, 10, 884, 3, 62],


In [14]:
max_sequence_len = max([len(x) for x in input_sequences])
input_sequences = np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding ='pre'))


In [15]:
max_sequence_len

11

In [16]:
input_sequences

array([[   0,    0,    0, ...,    0,    3,    2],
       [   0,    0,    0, ...,    3,    2,  313],
       [   0,    0,    0, ...,    2,  313, 1375],
       ...,
       [   0,    0,    0, ...,  493,  493, 3374],
       [   0,    0,    0, ...,  493, 3374,   14],
       [   0,    0,    0, ..., 3374,   14,   15]], dtype=int32)

In [17]:
input_sequences.shape

(15484, 11)

In [18]:
predectors,label = input_sequences[:,:-1],input_sequences[:,-1]

In [19]:
predectors.shape

(15484, 10)

In [20]:
label.shape

(15484,)

In [21]:
predectors

array([[   0,    0,    0, ...,    0,    0,    3],
       [   0,    0,    0, ...,    0,    3,    2],
       [   0,    0,    0, ...,    3,    2,  313],
       ...,
       [   0,    0,    0, ..., 3373,  493,  493],
       [   0,    0,    0, ...,  493,  493, 3374],
       [   0,    0,    0, ...,  493, 3374,   14]], dtype=int32)

In [22]:
label

array([   2,  313, 1375, ..., 3374,   14,   15], dtype=int32)

In [23]:
label = ku.to_categorical(label, num_classes=total_words)

In [24]:
label

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
label[0]

array([0., 0., 1., ..., 0., 0., 0.])

In [26]:
model = Sequential()
model.add(Embedding(total_words,240,input_length=max_sequence_len-1))
model.add(Bidirectional(LSTM(150)))
model.add(Dense(total_words,activation='softmax'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [27]:
adam = Adam(learning_rate=0.01)

In [28]:
model.compile(loss='categorical_crossentropy',optimizer=adam,metrics=['accuracy'])

In [ ]:
history = model.fit(predectors,label,epochs=100,verbose=2)

Epoch 1/100
484/484 - 42s - 86ms/step - accuracy: 0.0298 - loss: 6.8777
Epoch 2/100
484/484 - 45s - 93ms/step - accuracy: 0.0462 - loss: 6.6320
Epoch 3/100


In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

acc = history.history['accuracy']
loss = history.history['loss']

epochs = range(len(acc))
plt.plot(epochs,acc,'b',label='Training acuraccy',color='green')

plt.figure()

plt.plot(epochs,loss,'b',label="Traning loss")
plt.title('Traning loss')
plt.legend()

plt.show()

In [ ]:
seed_text =  "Thyself thy foe, to thy sweet self too"
next_words = 100

for _ in range(next_words):
  token_list = tokenizer.texts_to_sequences([seed_text])[0]
  token_list = pad_sequences([token_list],maxlen=max_sequence_len-1,padding='pre')
  Output_word = ' '
  for word_index in tokenizer.word_index.items():

    if word_index == np.argmax(predicted,axis=1):
      Output_word = word
      break
  seed_text += " " + Output_word
print(seed_text)

In [ ]:
seed_text = "Thyself thy foe, to thy sweet self too"
next_words = 100

for _ in range(next_words):
	token_list = tokenizer.texts_to_sequences([seed_text])[0]
	token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
	predicted = model.predict(token_list, verbose=0)
	output_word = ""
	for word, index in tokenizer.word_index.items():
		if index == np.argmax(predicted,axis=1):
			output_word = word
			break
	seed_text += " " + output_word
print(seed_text)